// <auto-generated />
using Clothing_Shop_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Clothing_Shop_Website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521130000_AddIsDefaultToUserAddress")]
    partial class AddIsDefaultToUserAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
